version: '2.1'

services:
  sampletypescript:
    image: sampletypescript
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  mongodb:
    container_name: mongos
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - backend
networks: 
  backend: